#!/bin/bash

# This script acts as an ad blocker by downloading a blocklist from the
# internet and symlinking it to /etc/hosts. User then runs the script to toggle
# the blocking on and off. Root privileges are needed to run this script.

set -e

HOSTS="/etc/hosts"
HOSTS_BACKUP="/etc/hosts.old"
BLOCKLIST="/etc/hosts.blocklist"
BLOCKLIST_SOURCE='https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
# BLOCKLIST_SOURCE='https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts'

# Download blocklist if not available
[ -f $BLOCKLIST ] ||  {
	echo "Downloading blocklist to '$BLOCKLIST'"
	curl -s $BLOCKLIST_SOURCE > $BLOCKLIST
}

# Backup original hosts file if in place
[ -f $HOSTS ] && [ ! -L $HOSTS ] && {
	echo "Moving original '$HOSTS' to '$HOSTS_BACKUP'"
	mv $HOSTS $HOSTS_BACKUP
}

# Light switch logic
if [ -L $HOSTS ]; then
	rm $HOSTS
	echo "Removed '$HOSTS'"
else
	ln -s $BLOCKLIST $HOSTS
	echo "Symlinked '$BLOCKLIST' to '$HOSTS'"
fi
