#!/bin/bash

# This script maps the first Wacom stylus device found to the primary screen.
# It also flips the orientation when `-L` option is provided. Script borrows
# from Tom Galvin's mapwacom, which is available here:
# https://gist.github.com/tom-galvin/6c19fe907945d735c045

DEVICE=$(xinput list --name-only | grep -i 'wacom' | grep -i 'stylus')
SCREEN=$(xrandr | grep 'connected primary' | awk '{print $1}')

if [ -z "$DEVICE" ]; then
	echo "No Wacom stylus device found." 1>&2
	exit 1
fi

read AREAX AREAY <<< $(xinput list-props "$DEVICE" |
	grep -i 'Wacom Tablet Area' | awk -F ', ' '{print $3, $4}')

read WIDTH HEIGHT <<< $(xrandr | grep "$SCREEN" |
	awk '{print $4}' | awk -F '[x+]' '{print $1, $2}')

RATIOAREAY=$(( AREAX * HEIGHT / WIDTH ))
RATIOAREAX=$(( AREAY * WIDTH / HEIGHT ))

if [ "$AREAY" -gt "$RATIOAREAY" ]; then
	NEWAREAX="$AREAX"
	NEWAREAY="$RATIOAREAY"
else
	NEWAREAX="$RATIOAREAX"
	NEWAREAY="$AREAY"
fi

if [ "$1" = '-L' ]; then
	xsetwacom --set "$DEVICE" Rotate half
fi

xsetwacom --set "$DEVICE" Area 0 0 "$NEWAREAX" "$NEWAREAY"
xsetwacom --set "$DEVICE" MapToOutput "$SCREEN"

echo "$DEVICE mapped to $SCREEN."
