#!/bin/bash

# This script wraps around nmcli and is used for managing wireless connections.
# It saves user's time by shortening the commands. In case of connecting to an
# unknown network, the script automatically asks for password.

WIFI="$(basename $0)"
VERB="$1"
ARG="$2"

print_help() {
	echo "Usage: $WIFI VERB [ARG]"
	echo
	echo "Verbs:"
	echo "  list            - list available networks"
	echo "  scan            - same as list, but refresh first"
	echo "  connect SSID    - connect to a network (asks for password if necessary)"
	echo "  disconnect SSID - disconnect from a network"
	echo "  on              - turn the wireless radio on"
	echo "  off             - turn the wireless radio off"
}

check_ssid() {
	[ "$ARG" ] || {
		echo "No SSID provided" 
		exit 1
	}
}

case "$1" in
	list)
		nmcli dev wifi list
		;;
	scan)
		nmcli dev wifi list --rescan yes
		;;
	connect)
		check_ssid
		if nmcli --get-value NAME conn | grep -q "$2"; then
			nmcli dev wifi connect "$2"
		else
			nmcli --ask dev wifi connect "$2"
		fi
		;;
	disconnect)
		check_ssid
		nmcli con down id "$2"
		;;
	on)
		nmcli radio wifi on
		;;
	off)
		nmcli radio wifi off
		;;
	*)
		print_help
		exit 1
		;;
esac
