#!/bin/bash

# This script wraps around XBPS package manager, shortening many often used
# commands. Syntax is inspired by APT. Root privileges are needed for some
# verbs.

set -u

XBPS="$(basename $0)"

print_help() {
	echo "Usage: $XBPS VERB [ARG]"
	echo
	echo "Verbs:"
	echo "  update      upgrade    install  remove"
	echo "  autoremove  autoclean  search   info"
	echo
	echo "Args:"
	echo "  install PKG..."
	echo "  remove PKG..."
	echo "  search PKG"
	echo "  info PKG"
}

case "$1" in
	update)
		xbps-install -S
		;;
	upgrade)
		xbps-install -u
		;;
	install)
		xbps-install "${@:2}"
		;;
	remove)
		xbps-remove "${@:2}"
		;;
	autoremove)
		xbps-remove -o
		;;
	autoclean)
		xbps-remove -O
		;;
	search)
		xbps-query -Rs "$2"
		;;
	info)
		xbps-query "$2"
		;;
	*)
		print_help
		exit 1
		;;
esac
